import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import { Suspense } from "react";
import Loading from "./loading";
import PageLoader from "./components/PageLoader";
import { BackgroundLines } from "./components/ui/background-lines";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Deep Reel",
  description: "Generated by create next app",
};

// Root layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        {/* ✅ Wrapper for relative positioning and full-page height */}
        <div className="relative min-h-screen w-full">
          {/* ✅ Full-height background that scrolls with the page */}
          <BackgroundLines className="absolute top-0 left-0 w-full h-full -z-10 pointer-events-none" children={undefined} />

          {/* ✅ Foreground: providers + app content */}
          <Providers>
            <PageLoader />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </Providers>
        </div>
      </body>
    </html>
  );
}
